### ISSUE TITLE
Multiple Interactive Grid in Region Display Selector makes buttons visible double

### ISSUE THREAD

**Issue by ymeijers** [mgoricki/apex-plugin-extend-ig-toolbar#5] opened 2018-07-26 15:28 UTC
Hi,

We have a page with 6 tabs with 4 interactive grids and 2 classic reports.
Now we used this plugin to add button two buttons to each interactive grid, but show it show like see screenshot. Chrome it works nicely but firefox it shows all buttons on all tabs.

What can we do?

![schermafbeelding 2018-07-26 om 17 28 03](https://user-images.githubusercontent.com/31541894/43272045-56360036-90f9-11e8-824c-8e3cae57de21.png)

**Comment by mgoricki** [comment] 2018-07-26 16:40
Are you using the latest version of a plug-in?
What APEX version are you at?

**Comment by mgoricki** [comment] 2018-08-22 10:08
Couldn't reproduce it. Closing issue.

**Closed by mgoricki** 2018-08-22 10:08 UTC
